# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch


exec-once = bash -c "swww-daemon & sleep 0.5 swww img ~/Pictures/level-up.png" #Used to start the swww daemon and set a wallpaper with a delay to avoid a race condition.
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
exec-once = /usr/libexec/polkit-kde-authentication-agent-1
exec-once = waybar
exec-once = sleep 1 && nm-applet
